Add : BGM now playable.
DrowningToast/untitled-blackjack pull request #46
Opened 2023-05-16 15:04 UTC by Suchanan239

Add sound hit , stand , background , win , when player join room , shuffle card 
Change Image All image of trumpCards
Add cardtarget point change to " / " + cardtarget
Add trumpStatusDisplay Class (wip)
-----------------------------------------------------------------------------
Edit Sound trump use 
Edit image file name

2023-05-16 17:08 UTC, DrowningToast requested changes

2023-05-16 17:08 UTC, DrowningToast commented on apps/blackjack-client/src/main/java/Internal/UserInterface/UIController.java
> +    private SoundPOJO sound;
ลบ

2023-05-16 17:08 UTC, DrowningToast commented on apps/blackjack-client/src/main/java/Internal/Websocket/Controller/EventHandlers/InitRound.java
>      public InitRound(UIController uiController){ this.uiController = uiController;}
SoundController ควรมีแค่ที่เดียว

2023-05-16 17:08 UTC, DrowningToast commented on apps/blackjack-client/src/main/java/UI/Gameplay/GameplayController.java
> +//        statusPlace.removeAll();
คอมเม้นแล้วลบด้วย

2023-05-16 19:25 UTC, DrowningToast requested changes

2023-05-16 19:25 UTC, DrowningToast commented on apps/blackjack-client/src/main/java/GameContext/TrumpCard/TrumpCardDisplay.java
> +
ถ้าทำแบบนี้ แล้วตอนที่ opponent กดใช้บ้าง จะไม่มีเสียงเล่นเลยบหรอ

2023-05-16 19:25 UTC, DrowningToast commented on apps/blackjack-client/src/main/java/GameContext/TrumpCard/TrumpCardDisplay.java
> +
อาจจะไปดักใน websocket event handler

2023-05-16 19:25 UTC, DrowningToast commented on apps/blackjack-client/src/main/java/Main/MainRunner.java
> +                    gameContext.getSoundController().playSound("backgroundCasinoSound");
ไปใส่ใน  loginController แทน

2023-05-18 05:47 UTC, Suchanan239 commented on apps/blackjack-client/src/main/java/Main/MainRunner.java
> +                    gameContext.getSoundController().playSound("backgroundCasinoSound");
changmang u said

2023-05-18 05:49 UTC, DrowningToast requested changes

2023-05-18 05:49 UTC, DrowningToast commented on apps/blackjack-client/src/main/java/GameContext/TrumpCard/TrumpCardDisplay.java
> +                System.out.println("kuyyyyyyyyyyyyyyyyyyyyy");
print kuy rai sus

2023-05-18 06:49 UTC, DrowningToast approved these changes
LGTM!

2023-05-18 06:53 UTC, merged