fix  & update : make all the trumpCards and trumpStatus playable in game
DrowningToast/untitled-blackjack pull request #48
Opened 2023-05-16 19:12 UTC by Corust1411

fix : make all the trumpCard playable 
add : trumpStatus to model 
update : trumpCards' displayName for log

2023-05-16 19:22 UTC, DrowningToast requested changes

2023-05-16 19:22 UTC, DrowningToast commented on apps/blackjack-client/src/main/java/GameContext/TrumpCard/TrumpCardController.java
> +        CARDS.put("ace", new TrumpCardPOJO("hit A.", "Draw Ace card from the deck. If this ard already on the desk, nothing will happen.", "ace", "DRAW", new ImageIcon("resources/HitA.PNG")));
เปลี่ยน desk -> table

2023-05-16 19:22 UTC, DrowningToast commented on apps/blackjack-client/src/main/java/GameContext/TrumpCard/TrumpCardController.java
> +        CARDS.put("ace", new TrumpCardPOJO("hit A.", "Draw Ace card from the deck. If this ard already on the desk, nothing will happen.", "ace", "DRAW", new ImageIcon("resources/HitA.PNG")));
สะกด ard ผิด

2023-05-16 19:22 UTC, DrowningToast commented on apps/blackjack-client/src/main/java/GameContext/TrumpCard/TrumpCardController.java
> +        CARDS.put("removeLastCard", new TrumpCardPOJO("removed your last card.", "Remove opponent's last card. *Does not effect opponent first 2 cards*", "removeLastCard", "ATTACK", new ImageIcon("re
remove your last card หรือว่า remove opponent last card กันแน่

2023-05-16 19:22 UTC, DrowningToast commented on apps/blackjack-client/src/main/java/GameContext/TrumpCard/TrumpCardController.java
> +        CARDS.put("removeLastCard", new TrumpCardPOJO("removed your last card.", "Remove opponent's last card. *Does not effect opponent first 2 cards*", "removeLastCard", "ATTACK", new ImageIcon("re
อ๋อ ทำไม arg แรกเป็น log อะ สลับได้ไหม

2023-05-16 19:22 UTC, DrowningToast commented on apps/blackjack-client/src/main/java/GameContext/TrumpCard/TrumpCardController.java
> +        CARDS.put("changePointsLimit25", new TrumpCardPOJO("change point target to 25.", "Change game win condition to 25 instead of 21.", "changePointsLimit25", "UTILITY", new ImageIcon("resources/C
game win -> round win

2023-05-16 19:22 UTC, DrowningToast commented on apps/blackjack-client/src/main/java/GameContext/TrumpCard/TrumpCardController.java
> +        CARDS.put("undoHit", new TrumpCardPOJO("remove their last card.", "Remove your latest card drawn. *Does not effect opponent first 2 cards*", "undoHit", "UTILITY", new ImageIcon("resources/Und
Doesn't affect opponent first 2 cards หรือ your first 2 cards?

2023-05-16 19:22 UTC, DrowningToast commented on apps/blackjack-client/src/main/java/Internal/Websocket/Controller/EventHandlers/UpdateTrumpCardsState.java
> +        ctx.getLogController().addLog(ctx.getPlayers()[0].getPOJO().getUsername()+"'s trumpCards has been updated.");
ไม่ต้อง log ก็ได้อันนี้ เพราะว่ามันจะขึ้นใหญ่มาก

2023-05-16 19:22 UTC, DrowningToast commented on apps/blackjack-client/src/main/java/GameContext/TrumpCard/TrumpCardController.java
> +        STATUSES.put("DENY_HIT", new TrumpStatusPOJO("DENY HIT", "Opponent cannot hit in this round.", "DENY_HIT",  new ImageIcon("resources/Deny_hit_Status.PNG")));
ไม่แน่ใจว่าเวลาเอา mouse hover status แล้วจะแสดงคำพูดเหมาะสมไหมเช่น

หาก hover ตัวเองจะได้ว่า
Opponent cannot hit in this round.

อาจจะเปลี่ยนเป็นอะไรที่แสดงได้ทั้งสองฝ่ายเช่น
The player cannot perform hit this round.

2023-05-16 19:23 UTC, Corust1411 commented on apps/blackjack-client/src/main/java/Internal/Websocket/Controller/EventHandlers/UpdateTrumpCardsState.java
> +        ctx.getLogController().addLog(ctx.getPlayers()[0].getPOJO().getUsername()+"'s trumpCards has been updated.");
ขึ้นรัวๆๆๆ

2023-05-17 04:25 UTC, DrowningToast requested changes

2023-05-18 05:23 UTC, DrowningToast requested changes

2023-05-18 05:23 UTC, DrowningToast commented on apps/blackjack-client/src/main/java/GameContext/TrumpCard/TrumpCardController.java
> +        CARDS.put("ace", new TrumpCardPOJO("hit A.", "Draw Ace card from the deck. If this card already on the table, nothing will happen.", "ace", "DRAW", new ImageIcon("resources/HitA.PNG")));
If this card **is** already on the table, nothing will happen.

2023-05-18 05:44 UTC, DrowningToast approved these changes

2023-05-18 05:44 UTC, merged